1st steps at making code Python 2 and 3 compatible
Running tests with Python 2.7.9 and 3.4.1, all but the
test_simplenote_is_unicode test pass so I wanted to make a commit at
this point.

Note: even once all tests pass, additional testing will be required to
be sure that the code works fine with both Python 2 and 3.

Under Python 2.7 the unicode error is:

    ~/Code/git...plenote.py * newissue13$ python2.7 tests/test_simplenote.py
    ........u..E...
    ======================================================================
    ERROR: test_simplenote_is_unicode (__main__.TestSimplenote)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tests/test_simplenote.py", line 151, in test_simplenote_is_unicode
	self.assertTrue(self.is_utf8(note["content"]))
      File "tests/test_simplenote.py", line 175, in is_utf8
	s.decode('utf-8')
      File "/usr/pkg/lib/python2.7/encodings/utf_8.py", line 16, in decode
	return codecs.utf_8_decode(input, errors, True)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u222e' in position 0: ordinal not in range(128)

    ----------------------------------------------------------------------
    Ran 15 tests in 126.764s

    FAILED (errors=1, unexpected successes=1)

Under Python 3.4 the unicode error is:

    ~/Code/git...plenote.py * newissue13$ python3.4 tests/test_simplenote.py
    ........u..E...
    ======================================================================
    ERROR: test_simplenote_is_unicode (__main__.TestSimplenote)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tests/test_simplenote.py", line 151, in test_simplenote_is_unicode
	self.assertTrue(self.is_utf8(note["content"]))
      File "tests/test_simplenote.py", line 175, in is_utf8
	s.decode('utf-8')
    AttributeError: 'str' object has no attribute 'decode'

    ----------------------------------------------------------------------
    Ran 15 tests in 132.261s

    FAILED (errors=1, unexpected successes=1)

The main changes are:

- Import `sys` so can use this to detect which version of Python is
  running
- Conditionally import urllib2 or urllib.request, etc depending on
  Python version. In Python 3 import urllib.request as urllib2 to utilise
  Python 2 code structure (which I've gone back to for now) for
  request/response
- Add monkey patching / subclassing of urllib2 back in for Python 2 as
  it's still needed, but for Python 3 subclass without making any
  changes.
- Work around differences in base64 encoding between 2 and 3 by trying
  for Python 3 first and checking for a TypeError, if that occurs it is
  assumed to be Python 2 and handled a different way.
- Also use TypeError to handle utf-8 in the token in different ways

References issue #13