Travis CI with just 1 version of python; tests can't be run concurrently
Testing against 2.5 fails with ImportError: No module named django.utils

Testing against 3.1 stops with The command "source
~/virtualenv/python3.1/bin/activate" failed and exited with 1 during
setup.

Testing against 3.2 fails with ImportError: cannot import name
Simplenote

2.6 and 2.7 both run, but since they run concurrently one or the other
will fail. This is because both are trying to access the same Simplenote
test account at the same time, both trying to add notes, delete notes,
etc at the same time, so it's not surprising that one (or both) could
fail at some point because the simplenote.py test suite is not designed
to be run concurrently.

So, for the time being, test against just version 2.7 as that will at
least provide meanigful build information.